services:
  mongodb:
    # Access mongosh from inside the container: docker exec -it mongodb mongosh
    container_name: mongodb
    image: mongo:8.0.6
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - "./db:/data/db:rw"

  fast-api:
    container_name: fast-api
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file: .env
    environment:
      DB_API_USER: ${DB_API_USER}
      DB_API_PWD: ${DB_API_PWD}
    volumes:
      - ./api:/api
    ports:
      - '8000:80'
    depends_on:
      - mongodb

  web:
    container_name: react-ts
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - fast-api

volumes:
  db:
    driver: local
    name: db
