services:
  spark-master:
    # Access running Spark master: docker exec -it spark-master bash
    container_name: spark-master
    build:
      context: ./spark
      dockerfile: Dockerfile
    image: spark-image
    entrypoint: /bin/bash
    command: -c "/opt/spark/sbin/start-master.sh; tail -f /dev/null"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./spark/scripts:/opt/spark/scripts
      - spark-logs:/opt/spark/spark-events
    env_file:
      - ./spark/.env.spark
      - .env
    environment:
      DB_ETL_USER: ${DB_ETL_USER}
      DB_ETL_PWD: ${DB_ETL_PWD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      HOST: ${HOST}
      MONGODB_PORT: ${MONGODB_PORT}
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker:
    container_name: spark-worker
    image: spark-image
    entrypoint: /bin/bash
    command: -c "/opt/spark/sbin/start-worker.sh  spark://spark-master:7077; tail -f /dev/null"
    depends_on:
      - spark-master
    env_file:
      - ./spark/.env.spark
      - .env
    environment:
      DB_ETL_USER: ${DB_ETL_USER}
      DB_ETL_PWD: ${DB_ETL_PWD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      HOST: ${HOST}
      MONGODB_PORT: ${MONGODB_PORT}
    volumes:
      - ./spark/scripts:/opt/spark/scripts
      - spark-logs:/opt/spark/spark-events

volumes:
  spark-logs:
