from enum import StrEnum


class ShakespeareWork(StrEnum):
    midsummer = "A Midsummer Night's Dream"
    allWell = "All's Well That Ends Well"
    cleopatra = "Antony and Cleopatra"
    asYouLikeIt = "As You Like It"
    coriolanus = "Coriolanus"
    cymbeline = "Cymbeline"
    hamlet = "Hamlet"
    henryIV_1 = "Henry IV, Part I"
    henryIV_2 = "Henry IV, Part 2"
    henryV = "Henry V"
    hentryVI_1 = "Henry VI, Part 1"
    hentryVI_2 = "Henry VI, Part 2"
    hentryVI_3 = "Henry VI, Part 3"
    caesar = "Julius Caesar"
    john = "King John"
    lear = "King Lear"
    loveLabor = "Love's Labor's Lost"
    lucrece = "Lucrece"
    macbeth = "Macbeth"
    measure = "Measure for Measure"
    muchAdo = "Much Ado About Nothing"
    othello = "Othello"
    pericles = "Pericles, Prince of Tyre"
    richardII = "Richard II"
    richardIII = "Richard III"
    romeo = "Romeo and Juliet"
    sonnets = "Sonnets"
    comedyOfErrors = "The Comedy of Errors"
    merchantOfVenice = "The Merchant of Venice"
    merryWives = "The Merry Wives of Windsor"
    phoenix = "The Phoenix and Turtle"
    taming = "The Taming of the Shrew"
    tempest = "The Tempest"
    twoGentlemen = "The Two Gentlemen of Verona"
    twoKinsmen = "The Two Noble Kinsmen"
    wintersTale = "The Winter's Tale"
    timon = "Timon of Athens"
    titus = "Titus Andronicus"
    troilus = "Troilus and Cressida"
    twelfthNight = "Twelfth Night"
    venus = "Venus and Adonis"
