name: Docker Build and Publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  detect-changes:
    runs-on: "ubuntu-22.04"
    outputs:
      changed: ${{ steps.detect.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Detect Changes
        id: detect
        uses: tchupp/actions-detect-directory-changes@v1

  build:
    name: "Build Sub-Project"
    runs-on: "ubuntu-22.04"
    strategy:
      matrix:
        project: ${{ fromJSON(needs.detect-changes.outputs.changed) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        run: echo ${{ secrets.GH_PAT }} | docker login ghcr.io -u rmnskb --password-stdin

      - name: Build Docker Image for ${{ matrix.project }}
        run: |
          docker build ./${{ matrix.project }} --file Dockerfile \
          --tag ghcr.io/rmnskb/bards-words-${{ matrix.project }}:latest

      - name: Push Docker Image for ${{ matrix.project }}
        run: |
          docker push ghcr.io/rmnskb/bards-words-${{ matrix.project }}:latest
